virtualMachines:
  - name: win11-vm2
    namespace: default
    storage: 60Gi
    hostPath: /var/vm/images/win11-2
    storageClassName: local-path
    cpuCores: 3
    memory: 12288Mi
    gpuDeviceName: intel.com/sriov-gpudevice
    secureBoot: false
    usePVC: false
    rdpPort: 3391
    cdiDv: vm2-win11-image
